name: Distribute Grain
on:
  # A new Cred interval every Sunday. We'll distribute Grain 5 minutes
  # after the new interval
  schedule:
    - cron: 5 0 * * 0 # 00:05 UTC, 16:05 PST
  push:
    branches:
      # allows us to test this workflow, or manually generate distributions
      # PRSs created from grain-trigger-* branches are targeted
      # on their immediate base branches, as opposed to master
      - "grain-trigger-*"

jobs:
  distribute-grain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "16"

      - name: Install Packages 🔧
        run: |
          yarn --frozen-lockfile

      - name: Load Data and Compute Cred 🧮
        run: |
          yarn load
          yarn sourcecred contributions
          yarn sourcecred credequate
          node scripts/wolf-turtle-bear.js
        env:
          SOURCECRED_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCECRED_DISCORD_TOKEN: ${{ secrets.SOURCECRED_DISCORD_TOKEN }}
          NODE_OPTIONS: "--max-old-space-size=8192"

      - name: Distribute Grain 💸
        env:
          ATTRIBUTIONS_RECIPIENT: ${{ secrets.ATTRIBUTIONS_RECIPIENT }}
          ATTRIBUTIONS: ${{ secrets.ATTRIBUTIONS }}
          SOURCECRED_DISCORD_TOKEN: ${{ secrets.SOURCECRED_DISCORD_TOKEN }}
        run: |
          yarn grain > grain_output.txt
          node scripts/post-process.js
          node scripts/send-dist.js
          rm distribution.csv
      - name: Set environment variables
        id: pr_details
        run: |
          echo "PULL_REQUEST_TITLE=Scheduled grain distribution for week ending $(date +"%B %dth, %Y")" >> $GITHUB_ENV
          description="This PR was auto-generated on $(date +%d-%m-%Y) \
            to add the latest grain distribution to our instance.

            $(cat grain_output.txt)"
          description="${description//'%'/'%25'}"
          description="${description//$'\n'/'%0A'}"
          description="${description//$'\r'/'%0D'}"
          echo "::set-output name=pr_body::$description"
          rm grain_output.txt

      - name: Create commit and PR for ledger changes
        id: pr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: generated-ledger
          branch-suffix: timestamp
          committer: credbot <credbot@users.noreply.github.com>
          # author appears to be overridden when the default github action
          # token is used for checkout
          author: credbot <credbot@users.noreply.github.com>
          commit-message: update calculated ledger
          title: ${{ env.PULL_REQUEST_TITLE }}
          body: ${{ steps.pr_details.outputs.pr_body }}
